FROM golang:1.21 AS build
WORKDIR /src
COPY . /src/
RUN env CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /usr/sbin/init-docker-systemd .

FROM rockylinux:8
COPY --from=build /usr/sbin/init-docker-systemd /usr/sbin/init-docker-systemd
ENTRYPOINT ["/usr/sbin/init-docker-systemd"]
